# Transposing a matrix

This notebook walks you through how to implement simple functions that transpose matrix $ A $, storing the result in matrix $ B $.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/325TransposeAlgorithm.png" alt="Transposing a matrix" width="75%">

## The routine

Write your <br>
<code> Transpose_unb_var1( A, B ) </code> <br>
routine, using the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> and the <code> laff.copy </code> routine.

In [1]:
# insert code here
import flame
import laff as laff

def Transpose_unb_var1(A, B):

    AL, AR = flame.part_1x2(A, \
                            0, 'LEFT')

    BT, \
    BB  = flame.part_2x1(B, \
                         0, 'TOP')

    while AL.shape[1] < A.shape[1]:

        A0, a1, A2 = flame.repart_1x2_to_1x3(AL, AR, \
                                             1, 'RIGHT')

        B0,  \
        b1t, \
        B2   = flame.repart_2x1_to_3x1(BT, \
                                       BB, \
                                       1, 'BOTTOM')

        #------------------------------------------------------------#

        laff.copy(a1, b1t)

        #------------------------------------------------------------#

        AL, AR = flame.cont_with_1x3_to_1x2(A0, a1, A2, \
                                            'LEFT')

        BT, \
        BB  = flame.cont_with_3x1_to_2x1(B0,  \
                                         b1t, \
                                         B2,  \
                                         'TOP')

    flame.merge_2x1(BT, \
                    BB, B)

## Testing

Let's quickly test the routine by creating a 5 x 4 matrix $ A $ and a 4 x 5 matrix $ B $ and then transposing $ A $, overwriting $ B $ with the result.

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,4 ) )
B = matrix( random.rand( 4,5 ) )

print( 'A ' )
print( A )


print( 'B before =' )
print( B )

A 
[[0.55335223 0.96011389 0.53181523 0.03551611]
 [0.30204556 0.04715879 0.65659992 0.07738024]
 [0.30588943 0.24064202 0.66861531 0.26907296]
 [0.21392682 0.94104252 0.51485744 0.67892637]
 [0.39021577 0.11552649 0.33815892 0.19566387]]
B before =
[[0.19900609 0.23048969 0.99241784 0.05098714 0.84209855]
 [0.4541099  0.7867206  0.01783766 0.28331313 0.08411515]
 [0.49506362 0.3574532  0.14750624 0.14222522 0.69051962]
 [0.80937899 0.70074828 0.51550819 0.85387541 0.69671195]]


In [3]:
Transpose_unb_var1( A, B )

print( 'A ' )
print( A )

print( 'B after =' )
print( B )

A 
[[0.55335223 0.96011389 0.53181523 0.03551611]
 [0.30204556 0.04715879 0.65659992 0.07738024]
 [0.30588943 0.24064202 0.66861531 0.26907296]
 [0.21392682 0.94104252 0.51485744 0.67892637]
 [0.39021577 0.11552649 0.33815892 0.19566387]]
B after =
[[0.55335223 0.30204556 0.30588943 0.21392682 0.39021577]
 [0.96011389 0.04715879 0.24064202 0.94104252 0.11552649]
 [0.53181523 0.65659992 0.66861531 0.51485744 0.33815892]
 [0.03551611 0.07738024 0.26907296 0.67892637 0.19566387]]


Bingo, it seems to work!

## Try it yourself (Homework 3.2.5.3)

Now, an alternative routine that accesses the matrix by rows.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the routine <br>
<code> Transpose_unb_var2( A, B )</code>.<br>

In [4]:
# insert code here
def Transpose_unb_var2(A, B):

    AT, \
    AB  = flame.part_2x1(A, \
                         0, 'TOP')

    BL, BR = flame.part_1x2(B, \
                            0, 'LEFT')

    while AT.shape[0] < A.shape[0]:

        A0,  \
        a1t, \
        A2   = flame.repart_2x1_to_3x1(AT, \
                                       AB, \
                                       1, 'BOTTOM')

        B0, b1, B2 = flame.repart_1x2_to_1x3(BL, BR, \
                                             1, 'RIGHT')

        #------------------------------------------------------------#

        laff.copy(a1t, b1)

        #------------------------------------------------------------#

        AT, \
        AB  = flame.cont_with_3x1_to_2x1(A0,  \
                                         a1t, \
                                         A2,  \
                                         'TOP')

        BL, BR = flame.cont_with_1x3_to_1x2(B0, b1, B2, \
                                            'LEFT')

    flame.merge_1x2(BL, BR, B)

Test your routine with the following

In [5]:
A = matrix( random.rand( 5,4 ) )
B = matrix( random.rand( 4,5 ) )

print( 'A ' )
print( A )


print( 'B before =' )
print( B )

A 
[[0.53439853 0.61498768 0.05113731 0.59815442]
 [0.54087705 0.68433059 0.68986128 0.61688147]
 [0.79576232 0.17346618 0.76947475 0.86142603]
 [0.98677079 0.59940608 0.10450693 0.9227491 ]
 [0.98295528 0.1132598  0.41633315 0.97910179]]
B before =
[[0.0308236  0.17621828 0.98074084 0.79325934 0.83924103]
 [0.38072765 0.71980277 0.15907449 0.38834001 0.50719516]
 [0.09911941 0.00445134 0.89570633 0.83807096 0.55154412]
 [0.15587083 0.35959331 0.08408129 0.05803455 0.59834753]]


In [6]:
Transpose_unb_var2( A, B )

print( 'A ' )
print( A )

print( 'B after =' )
print( B )

A 
[[0.53439853 0.61498768 0.05113731 0.59815442]
 [0.54087705 0.68433059 0.68986128 0.61688147]
 [0.79576232 0.17346618 0.76947475 0.86142603]
 [0.98677079 0.59940608 0.10450693 0.9227491 ]
 [0.98295528 0.1132598  0.41633315 0.97910179]]
B after =
[[0.53439853 0.54087705 0.79576232 0.98677079 0.98295528]
 [0.61498768 0.68433059 0.17346618 0.59940608 0.1132598 ]
 [0.05113731 0.68986128 0.76947475 0.10450693 0.41633315]
 [0.59815442 0.61688147 0.86142603 0.9227491  0.97910179]]


## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.