# The Set_to_zero routine

This notebook walks you through how to implement a simple function that sets all elements of a given matrix, 
stored in numpy matrix A, to zero.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/321ZeroAlgorithm.png" alt="Set matrix to zero algorithm" width="50%">

## The routine

The specific laff function we will use is laff.zerov which, when given a row or column vector (stored as a 1 x n or n x 1 matrix) will zero that vector.  The vectors to be zeroed will actually be parts of the matrix A that we overwrite with zeroes.  

The flame functions should be self-explanatory if you put the below next to the algorithm for setting a matrix to the zero, expressed using the FLAME notation.

It is the merge_1x2 routine that does require an explanation.  The problem is that we want to overwrite A with the result.  That routine takes AT, AB, and copies them back into A.

Follow along with the video, using the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
import flame
import laff as laff

def set_to_zero_unb_var1(A):

    AL, AR = flame.part_1x2(A, \
                            0, 'LEFT')

    while AL.shape[1] < A.shape[1]:

        A0, a1, A2 = flame.repart_1x2_to_1x3(AL, AR, \
                                             1, 'RIGHT')

        #------------------------------------------------------------#
        laff.zerov(a1)
        #------------------------------------------------------------#

        AL, AR = flame.cont_with_1x3_to_1x2(A0, a1, A2, \
                                            'LEFT')

## Testing

Let's quickly test the routine by creating a 5 x 5 matrix and then setting it to zero.

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,4 ) )

print( 'A before =' )
print( A )

A before =
[[0.02662035 0.05231089 0.49335357 0.44744261]
 [0.04231373 0.6007675  0.41025977 0.45342552]
 [0.08566831 0.13105654 0.39841025 0.01424154]
 [0.51840324 0.91547921 0.6312357  0.67184407]
 [0.44999942 0.96957197 0.04554298 0.62597249]]


In [4]:
set_to_zero_unb_var1( A )

print( 'A after =' )
print( A )

A after =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Bingo, it seems to work!

## Try it yourself (homework 3.2.1.2)

Now, one could alternatively set a matrix to zero by rows.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the function Set_to_zero_unb_var2( A ) that overwrites A with zeroes one row at a time.

In [5]:
#insert code here
def set_to_zero_unb_var2(A):

    AT, \
    AB  = flame.part_2x1(A, \
                         0, 'TOP')

    while AT.shape[0] < A.shape[0]:

        A0,  \
        a1t, \
        A2   = flame.repart_2x1_to_3x1(AT, \
                                       AB, \
                                       1, 'BOTTOM')

        #------------------------------------------------------------#
        laff.zerov(a1t)
        #------------------------------------------------------------#

        AT, \
        AB  = flame.cont_with_3x1_to_2x1(A0,  \
                                         a1t, \
                                         A2,  \
                                         'TOP')

Test your routine with the following

In [6]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,4 ) )

print( 'A before =' )
print( A )

set_to_zero_unb_var2( A )
print( 'A after =' )
print( A )

A before =
[[0.20763292 0.1033688  0.67313258 0.05967489]
 [0.01705954 0.48108876 0.21954565 0.95472558]
 [0.99812887 0.21868281 0.44991276 0.28535584]
 [0.34360598 0.75613258 0.80766913 0.82572942]
 [0.96422065 0.3615378  0.3237603  0.25718908]]
A after =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.