# The Set_to_identity routine

This notebook walks you through how to implement simple functions that set a square matrix to the identity matrix.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/322IdentityAlgorithm.png" alt="Set matrix to zero algorithm" width="50%">

## The routine

The specific laff functions we will use are 
<ul>
<li> <code> laff.zerov </code> which, when given a row or column vector (stored as a 1 x n or n x 1 matrix) will zero that vector.  </li>
<li> <code> laff.onev </code> which, when given a row or column vector (stored as a 1 x n or n x 1 matrix) will set all components of that vector to one.  We will use it with the scalar <code> alpha11 </code>.  </li>
</ul>

Follow along with the video, using the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
# insert code here
import flame
import laff as laff

def Set_to_identity_unb_var1(A):

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while ATL.shape[0] < A.shape[0]:

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.zerov(a01)
        laff.onev(alpha11)
        laff.zerov(a21)

        #------------------------------------------------------------#

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)

## Testing

Let's quickly test the routine by creating a 5 x 5 matrix and then setting it to the identity.

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )

print( 'A before =' )
print( A )

A before =
[[0.94564632 0.54630482 0.5383817  0.13528951 0.63005595]
 [0.34384229 0.21790505 0.94855262 0.09878297 0.94481023]
 [0.92241409 0.70746845 0.44926839 0.89789732 0.64161364]
 [0.48782938 0.43221088 0.98156395 0.65605597 0.50794532]
 [0.56231645 0.1561918  0.91853812 0.26937939 0.65815129]]


In [3]:
Set_to_identity_unb_var1( A )

print( 'A after =' )
print( A )

A after =
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Bingo, it seems to work!

## Try it yourself (Homework 3.2.2.2)

Now, one could alternatively set a matrix to zero by rows.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the function Set_to_identity_unb_var2( A ) that overwrites A with the identity one row at a time.

In [4]:
# insert code here
def Set_to_identity_unb_var2(A):

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while ATL.shape[0] < A.shape[0]:

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.zerov(a10t)
        laff.onev(alpha11)
        laff.zerov(a12t)

        #------------------------------------------------------------#

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)

Test your routine with the following

In [5]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )

print( 'A before =' )
print( A )

Set_to_identity_unb_var2( A )
print( 'A after =' )
print( A )

A before =
[[0.34059235 0.41617618 0.22805821 0.84801305 0.4902998 ]
 [0.32372715 0.96098215 0.78430822 0.77167096 0.65717524]
 [0.07844176 0.97730413 0.33996606 0.70306454 0.725139  ]
 [0.03642824 0.75853446 0.3975946  0.79457466 0.52187807]
 [0.26035199 0.46094401 0.96255201 0.98369814 0.58214192]]
A after =
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.