# The Set_to_diagonal_matrix routine

This notebook walks you through how to implement simple functions that set the diagonal elements of a square matrix to the components of a given vector.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/323DiagonalAlgorithm.png" alt="Set matrix to a diagonal matrix algorithm" width="75%">

## The routine <br> <code> Set_to_diagonal_matrix_unb_var1( d, A ) </code>

This routine sets the diagonal elements of $ A $ to the components of vector $ d$, and sets the off-diagonal elements to zero.

The specific laff functions we will use are 
<ul>
<li> <code> laff.zerov </code> which, when given a row or column vector (stored as a 1 x n or n x 1 matrix) will zero that vector.  </li>
<li> <code> laff.copy </code> which copies a vector to a vector.  We will use it to copy a scalar to a scalar.  </li>
</ul>

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
# insert code here
import flame
import laff as laff

def Set_to_diagonal_matrix_unb_var1(d, A):

    dT, \
    dB  = flame.part_2x1(d, \
                         0, 'TOP')

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while dT.shape[0] < d.shape[0]:

        d0,     \
        delta1, \
        d2      = flame.repart_2x1_to_3x1(dT, \
                                          dB, \
                                          1, 'BOTTOM')

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.zerov(a01)
        laff.copy(delta1, alpha11)
        laff.zerov(a21)

        #------------------------------------------------------------#

        dT, \
        dB  = flame.cont_with_3x1_to_2x1(d0,     \
                                         delta1, \
                                         d2,     \
                                         'TOP')

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)

## Testing

Let's quickly test the routine by creating a 5 x 5 matrix and vector of size 5 and then setting the matrix to the diagonal matrix with the components of the vector on its diagonal

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )
d = matrix( random.rand( 5,1 ) )

print( 'A before =' )
print( A )

print( 'd before =' )
print( d )

A before =
[[0.89620008 0.37396754 0.05758156 0.14556726 0.18302347]
 [0.25881271 0.06205897 0.15482306 0.2736633  0.78393562]
 [0.50008733 0.32849409 0.71634702 0.20562    0.39378271]
 [0.8666314  0.39693874 0.62925369 0.24091628 0.85120012]
 [0.49250397 0.26872635 0.8010048  0.5601199  0.67839038]]
d before =
[[0.47676993]
 [0.9888788 ]
 [0.8931911 ]
 [0.30750311]
 [0.34472437]]


In [3]:
Set_to_diagonal_matrix_unb_var1( d, A )

print( 'A after =' )
print( A )

A after =
[[0.47676993 0.         0.         0.         0.        ]
 [0.         0.9888788  0.         0.         0.        ]
 [0.         0.         0.8931911  0.         0.        ]
 [0.         0.         0.         0.30750311 0.        ]
 [0.         0.         0.         0.         0.34472437]]


Bingo, it seems to work!

## Try it yourself (Homework 3.2.3.3)

Now, one could alternatively sets the matrix to the diagonal matrix by rows.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the function Set_to_diagonal_matrix_unb_var2( d, A ) that overwrites A  one row at a time.

In [4]:
# insert code here
def Set_to_diagonal_matrix_unb_var2(d, A):

    dT, \
    dB  = flame.part_2x1(d, \
                         0, 'TOP')

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while dT.shape[0] < d.shape[0]:

        d0,     \
        delta1, \
        d2      = flame.repart_2x1_to_3x1(dT, \
                                          dB, \
                                          1, 'BOTTOM')

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.zerov(a10t)
        laff.copy(delta1, alpha11)
        laff.zerov(a12t)

        #------------------------------------------------------------#

        dT, \
        dB  = flame.cont_with_3x1_to_2x1(d0,     \
                                         delta1, \
                                         d2,     \
                                         'TOP')

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)

Test your routine with the following

In [5]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )
d = matrix( random.rand( 5,1 ) )

print( 'A before =' )
print( A )

print( 'd before =' )
print( d )

Set_to_diagonal_matrix_unb_var2( d, A )

print( 'A after =' )
print( A )

A before =
[[0.97738798 0.59643233 0.8764531  0.70928917 0.38438644]
 [0.79125623 0.23127868 0.87888948 0.42282653 0.69680034]
 [0.77116089 0.94229626 0.7469634  0.62995147 0.03380954]
 [0.46025737 0.80441679 0.85616878 0.21149111 0.71899128]
 [0.05533325 0.19711256 0.80926041 0.82757903 0.60803493]]
d before =
[[0.08174105]
 [0.34574727]
 [0.99154629]
 [0.55266219]
 [0.36060458]]
A after =
[[0.08174105 0.         0.         0.         0.        ]
 [0.         0.34574727 0.         0.         0.        ]
 [0.         0.         0.99154629 0.         0.        ]
 [0.         0.         0.         0.55266219 0.        ]
 [0.         0.         0.         0.         0.36060458]]


## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.