# Matrix-vector multiplication via dot products

This notebook walks you through how to implement $ y := A x + y $ via dot products.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/341Mvmult_n_unb_var1.png" alt="Matrix-vector multiplication via dot products algorithm" width="75%">

## The routine <br> <code> Mvmult_n_unb_var1( A, x, y ) </code>

This routine, given $ A \in \mathbb{R}^{m \times n} $, $ x \in \mathbb{R}^n $, and $ y \in \mathbb{R}^m $, computes $ y := A x + y $.  The "_n_" indicates this is the "no transpose" matrix-vector multiplication.  What this means will become clear next week.

The specific laff functions we will use are 
<ul>
<li> <code> laff.dots( x, y, alpha ) </code> which computes $ \alpha := x^T y + \alpha $.  </li>
</ul>

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
# insert code here
import flame
import laff as laff

def Mvmult_n_unb_var1(A, x, y):

    AT, \
    AB  = flame.part_2x1(A, \
                         0, 'TOP')

    yT, \
    yB  = flame.part_2x1(y, \
                         0, 'TOP')

    while AT.shape[0] < A.shape[0]:

        A0,  \
        a1t, \
        A2   = flame.repart_2x1_to_3x1(AT, \
                                       AB, \
                                       1, 'BOTTOM')

        y0,   \
        psi1, \
        y2    = flame.repart_2x1_to_3x1(yT, \
                                        yB, \
                                        1, 'BOTTOM')

        #------------------------------------------------------------#

        laff.dots(a1t, x, psi1)

        #------------------------------------------------------------#

        AT, \
        AB  = flame.cont_with_3x1_to_2x1(A0,  \
                                         a1t, \
                                         A2,  \
                                         'TOP')

        yT, \
        yB  = flame.cont_with_3x1_to_2x1(y0,   \
                                         psi1, \
                                         y2,   \
                                         'TOP')

    flame.merge_2x1(yT, \
                    yB, y)

## Testing

Let's quickly test the routine by creating a 4 x 3 matrix and related vectors, performing the computation.

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 4,3 ) )
x = matrix( random.rand( 3,1 ) )
y = matrix( random.rand( 4,1 ) )
yold = matrix( random.rand( 4,1 ) )

print( 'A before =' )
print( A )

print( 'x before =' )
print( x )

print( 'y before =' )
print( y )

A before =
[[0.7837673  0.5100504  0.18557742]
 [0.48964018 0.14872158 0.89073081]
 [0.5452239  0.74337272 0.5214172 ]
 [0.16991335 0.04467669 0.20320497]]
x before =
[[0.76461595]
 [0.05680522]
 [0.28787295]]
y before =
[[0.59757096]
 [0.61581178]
 [0.38583924]
 [0.41117816]]


In [3]:
laff.copy( y, yold )   # save the original vector y

Mvmult_n_unb_var1( A, x, y )

print( 'y after =' )
print( y )

print( 'y - ( A * x + yold ) = ' )
print( y - ( A * x + yold ) )

y after =
[[1.27924819]
 [1.25506394]
 [0.99505549]
 [0.6021317 ]]
y - ( A * x + yold ) = 
[[-2.22044605e-16]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


Bingo, it seems to work!  (Notice that we are doing floating point computations, which means that due to rounding you may not get an exact "0".)

## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.