## Implementing a (vector) copy routine

### Preliminaries

<p><font color=red> Copy this notebook so that you don't corrupt the original!  Then you can "play" with the copy of the notebook all you want! </font> </p>

<p>This particular notebook does everything for you if you follow along with the video and type in code produced there.  You will be able to try it yourself in subsequent notebooks that implement other operations.</p>

Let's start by importing numpy and creating a vector $ x = \left( \begin{array}{r} 1 \\ 2 \\ 3 \end{array} \right) $ and a vector $ y = \left( \begin{array}{r} 0 \\ -1 \\ -2 \end{array} \right) $.  

Execute the code in the box by clicking in the box and then on "Cell -> Run".  Alternative, click on the box and push "Shift" and "Return" (or "Enter") together.

In [1]:
# This imports a package called "numpy" that will make working with matrices 
# simpler. We choose to call this package by the abbreviation np
import numpy as np
# create two two-dimensional matrices of only one column each.  
# In the future we will also think of (column) 
# vectors as matrices with only one column.
x = np.matrix("1; 2; 3"); y = np.matrix("0; -1; -2")
print( 'x = ' )
print( x )

print( 'y = ' )
print( y )

x = 
[[1]
 [2]
 [3]]
y = 
[[ 0]
 [-1]
 [-2]]


Now, let's use assignment to copy x into vector y:

(Again: "Shift" and "Return" at the same time!)

In [2]:
y = x

print( 'y = ' )
print( y )

y = 
[[1]
 [2]
 [3]]


Hmmm, it seems like it all worked.  The problem is that, in this situation, Python does a "shallow copy".  If you change a value in x, then that value also changes in y.  In other words, y is just a reference to the same data that x references.

We illustrate this by setting the second entry in $ x $ to a new value and printing both <code> x </code> and <code> y </code>.

In [3]:
x[ 1,0 ] = -999    # notice that Python starts indexing at 0.  (You count 0, 1, ...)
                   # Given that a vector of length n is an (n x 1) matrix, x[ 1,0 ] refers to 
                   # the second component [1] of vector x. The [0] idicates that we are working
                   # with the first column of the matrix, but here the matrix only has one column!
print( 'x = ' )
print( x )
print( 'y = ' )
print( y )

x = 
[[   1]
 [-999]
 [   3]]
y = 
[[   1]
 [-999]
 [   3]]


To fix this, we could write a loop that copies the entries of x into the vector y.  Let's start by resetting the values in y:

In [4]:
x = np.matrix( '1;2;3' )
print( 'x = ' )
print( x )

y = np.matrix( '0;-1;-2' )
print( 'y = ' )
print( y )

x = 
[[1]
 [2]
 [3]]
y = 
[[ 0]
 [-1]
 [-2]]


Now, we want to copy the three entries in x into the three entries in y using a "for" loop:

In [5]:
for i in range(3):
    y[i, 0] = x[i, 0]

print( 'y = ' )
print( y )

y = 
[[1]
 [2]
 [3]]


If we now change the second value in x, the contents of y do not change:

In [6]:
x[1, 0] = -999
print( 'x = ' )
print( x )
print( 'y = ' )
print( y )

x = 
[[   1]
 [-999]
 [   3]]
y = 
[[1]
 [2]
 [3]]


### Copy as a simple routine

Clearly, writing the "for loop" every time you want to copy a vector would be very cumbersome.  For this reason, we are going to write a routine, copy( x, y ), that copies the contents of vector x to vector y.  <font color=red> (Note: there <i>are</i> other ways of doing a "deep copy" in Python.  However, the whole point of writing these routines is to help learn the material in this course.  This is not a course in which we teach you Python beyond what you need to better understand linear algebra.) </font>

Here is what it means to copy a vector of size $ m $:
$$
\left( \begin{array}{c}
\psi_0 \\
\psi_1 \\
\vdots \\
\psi_{m-1}
\end{array}
\right)
:=
\left( \begin{array}{c}
\chi_0 \\
\chi_1 \\
\vdots \\
\chi_{m-1}
\end{array}
\right)
$$

As an algorithm this can be written as
<p>
<b> for </b> $ i = 0, \ldots , m-1 $  <br>
 $ ~~~ \psi_i := \chi_i $ <br>
<b> endfor </b>
</p>

<p>
This translates into the following routine:
</p>

In [7]:
def copy(x, y):
    m, n = x.shape
    for i in range(m):
        y[i, 0] = x[i, 0]

Be sure the run the above box, or this notebook won't know about the routine!!!

Now, if you execute

In [8]:
copy( x, y )

print( 'x = ' )
print( x )

print( 'y = ' )
print( y )

x = 
[[   1]
 [-999]
 [   3]]
y = 
[[   1]
 [-999]
 [   3]]


you notice that vector x has been copied to vector y.  And if we change values in x, the values in y don't change:

In [9]:
x[ 2,0 ] = 111

print( 'x = ' )
print( x )

print( 'y = ' )
print( y )

x = 
[[   1]
 [-999]
 [ 111]]
y = 
[[   1]
 [-999]
 [   3]]


### A complete copy function

As we develop our library, we are really going to need a copy routine that can copy rows from a matrix into a column vector, columns of a matrix into a vector, a row of a matrix into a column of a matrix, and all such combinations.  As a result, what we really want is a copy routine that works when x and y are column and/or row vectors, in all combinations.  It also should notify us if we try to copy between vectors that are not of the same size.  We now give a complete copy function.

From our past experience teaching this course, we've noticed that the details of this routine, and others like it, get confusing to those who have not programmed before and/or have not programmed with Python before.  So, don't worry too much if you don't understand it all.  We give it more for those who are interested in the details than as a necessary part of the course.

In [10]:
from numpy import matrix
from numpy import shape 

def copy(x, y):
    """
    Compute y = x, overwriting y
    
    x and y can be row and/or column vectors.  If necessary, an
    implicit transposition happens.
    """
    
    assert type(x) is matrix and len(x.shape) is 2, \
           "laff.copy: vector x must be a 2D numpy.matrix"

    assert type(y) is matrix and len(y.shape) is 2, \
           "laff.copy: vector y must be a 2D numpy.matrix"

    m_x, n_x = x.shape
    m_y, n_y = y.shape
    
    assert m_x is 1 or n_x is 1, "laff.copy: x is not a vector"
    assert m_y is 1 or n_y is 1, "laff.copy: y is not a vector"

    if m_x is 1 and m_y is 1: # x is a row, y is a row
        assert n_x == n_y, "laff.copy: size mismatch between x and y"
        for i in range(n_x): y[0, i] = x[0, i]
            
    elif n_x is 1 and n_y is 1: # x is a column, y is a column
        assert m_x == m_y, "laff.copy: size mismatch between x and y"
        for i in range(m_x): y[i, 0] = x[i, 0]
            
    elif m_x is 1 and n_y is 1: # x is a row, y is a column
        assert n_x == m_y, "laff.copy: size mismatch between x and y"
        for i in range(n_x): y[i, 0] = x[0, i]
            
    elif n_x is 1 and m_y is 1: # x is a column, y is a row
        assert m_x == n_y, "laff.copy: size mismatch between x and y"
        for i in range(m_x): y[0, i] = x[i, 0]


For a line-by-line explanation, watch the video!

### Test the code

#### Copy a row to a row

In [11]:
x = np.matrix( '1 2 3' )
y = np.matrix('0 -2 -3')

print( "x = " )
print( x )
print( "y = " )
print( y )

copy( x, y )
print( "y = " )
print( y )

assert np.array_equal(x,y), "error!"

x = 
[[1 2 3]]
y = 
[[ 0 -2 -3]]
y = 
[[1 2 3]]


In [13]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

x = np.matrix( '1 2 3' )
y = np.matlib.zeros( (1,3), dtype=int)    # create a 1 x 3 matrix of zeros
print("From row to row", "x = ", x, "y = ", y, sep="\n")
copy(x,y)
print("\ny = ", y, "________________", sep="\n")

x = np.matrix( '1;\
                2;\
                3' )
y = np.matlib.zeros( (3,1), dtype=int)
print( "\nFrom column to column", "x = ", x, "y = ", y, sep="\n")
copy(x,y)
print("\ny = ", y, "________________", sep="\n")

x = np.matrix( '1 2 3' )
y = np.matlib.zeros( (3,1), dtype=int)
print( "\nFrom row to column", "x = ", x, "y = ", y, sep="\n")
copy(x, y)
print("\ny = ", y, "________________", sep="\n")

x = np.matrix( '1;\
                2;\
                3' )
y = np.matlib.zeros(( 1,3), dtype=int)
print( "\nFrom column to row", "x = ", x, "y = ", y, sep="\n")
copy(x, y)
print("\ny = ", y, "________________", sep="\n")

-----SLAP_copy tests-----

From row to row
x = 
[[1 2 3]]
y = 
[[0 0 0]]

y = 
[[1 2 3]]
________________

From column to column
x = 
[[1]
 [2]
 [3]]
y = 
[[0]
 [0]
 [0]]

y = 
[[1]
 [2]
 [3]]
________________

From row to column
x = 
[[1 2 3]]
y = 
[[0]
 [0]
 [0]]

y = 
[[1]
 [2]
 [3]]
________________

From column to row
x = 
[[1]
 [2]
 [3]]
y = 
[[0 0 0]]

y = 
[[1 2 3]]
________________


Now, let's see what happens if we try to do something like copying a row of the wrong length into a column.  <font color="red"> Don't worry about the fact that you are getting error messages.  The whole point of the next few cells is to illustrate how errors are reported. </font>

In [14]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

x = np.matrix( '1 2 3 4' )
y = np.matlib.zeros( (1,3), dtype=int)
print("From row to row", "x = ", x, "y = ", y, sep="\n")
copy(x,y)
print("\ny = ", y, "________________", sep="\n")

-----SLAP_copy tests-----

From row to row
x = 
[[1 2 3 4]]
y = 
[[0 0 0]]


AssertionError: laff.copy: size mismatch between x and y

In [15]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

x = np.matrix( '1;\
                2;\
                3;\
                4' )
y = np.matlib.zeros( (3,1), dtype=int)
print( "\nFrom column to column", "x = ", x, "y = ", y, sep="\n")
copy(x,y)
print("\ny = ", y, "________________", sep="\n")

-----SLAP_copy tests-----


From column to column
x = 
[[1]
 [2]
 [3]
 [4]]
y = 
[[0]
 [0]
 [0]]


AssertionError: laff.copy: size mismatch between x and y

In [16]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

x = np.matrix( '1 2 3 4' )
y = np.matlib.zeros( (3,1), dtype=int)
print( "\nFrom row to column", "x = ", x, "y = ", y, sep="\n")
copy(x, y)
print("\ny = ", y, "________________", sep="\n")

-----SLAP_copy tests-----


From row to column
x = 
[[1 2 3 4]]
y = 
[[0]
 [0]
 [0]]


AssertionError: laff.copy: size mismatch between x and y

In [17]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

x = np.matrix( '1;\
                2;\
                3;\
                4' )
y = np.matlib.zeros(( 1,3), dtype=int)
print( "\nFrom column to row", "x = ", x, "y = ", y, sep="\n")
copy(x, y)
print("\ny = ", y, "________________", sep="\n")

-----SLAP_copy tests-----


From column to row
x = 
[[1]
 [2]
 [3]
 [4]]
y = 
[[0 0 0]]


AssertionError: laff.copy: size mismatch between x and y

Finally, let's see if we can copies rows and/or columns in matrices


In [18]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

A = np.matrix( '1  2  3  4;\
                5  6  7  8;\
                9 10 11 12' )
B = np.matlib.zeros( (3,4), dtype=int)
print("From row to row", "A = ", A, "B = ", B, sep="\n")
copy(A[1,:],B[0,:])
print("\nB = ", B, "________________", sep="\n")

-----SLAP_copy tests-----

From row to row
A = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
B = 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

B = 
[[5 6 7 8]
 [0 0 0 0]
 [0 0 0 0]]
________________


In [19]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

A = np.matrix( '1  2  3  4;\
                5  6  7  8;\
                9 10 11 12' )
B = np.matlib.zeros( (3,4), dtype=int)
print("From column to column", "A = ", A, "B = ", B, sep="\n")
copy(A[:,0],B[:,1])
print("\nB = ", B, "________________", sep="\n")

-----SLAP_copy tests-----

From column to column
A = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
B = 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

B = 
[[0 1 0 0]
 [0 5 0 0]
 [0 9 0 0]]
________________


## Copying rows and columns of matrices

We haven't discussed matrices yet.  For now, just think of them as two dimensional arrays of numbers.  We illustrate how our general copy routine can copy rows to columns, columns to columns, and so forth.

In [20]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

A = np.matrix( '1  2  3  4; \
                5  6  7  8; \
                9 10 11 12' )
B = np.matlib.zeros( (4,3), dtype=int)
print("From row to column", "A = ", A, "B = ", B, sep="\n")
copy(A[1,:],B[:,0])
print("\nB = ", B, "________________", sep="\n")

-----SLAP_copy tests-----

From row to column
A = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
B = 
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

B = 
[[5 0 0]
 [6 0 0]
 [7 0 0]
 [8 0 0]]
________________


In [21]:
import numpy.matlib

print("-----SLAP_copy tests-----\n")

A = np.matrix( '1  2  3  4;\
                5  6  7  8;\
                9 10 11 12' )
B = np.matlib.zeros( (4,3), dtype=int)
print("From column to row", "A = ", A, "B = ", B, sep="\n")
copy(A[:,1],B[0,:])
print("\nB = ", B, "________________", sep="\n")

-----SLAP_copy tests-----

From column to row
A = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
B = 
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

B = 
[[ 2  6 10]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]
________________


## The laff library <code> copy </code> routine

The above routine is part of a library routine as part of the <code> laff </code> library.  To use it you will have to do <br>
<br>
<code> import laff </code>
<br>
<br>
after which you can use the routine by calling
<br>
<br>
<code> laff.copy( x, y ) </code>

In [ ]:
import laff

x = np.matrix( '1;\
                2;\
                3' )
y = np.matrix( '-1;\
                 0;\
                 2' )

laff.copy( x, y )

print( "x = " )
print( x )

print( "y = " )
print( y )

<font color="red"> That's all!  Next, you will get to practice writing some code.  But don't panic: we'll get you through it. </font>