# Matrix-vector multiplication multiply with transpose matrix

This notebook walks you through how to implement $ y := A^T x + y $ <i> without explicitly transposing the matrix</i>.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff" and "import flame" statements.

## Algorithm (via dot products)

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/431Mvmult_n_unb_var1.png" alt="Matrix-vector multiplication via dot products algorithm" width="48%"><image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/431Mvmult_t_unb_var1.png" alt="Matrix-vector multiplication via dot products algorithm" width="48%">


Above, you find two algorithms.  The one on the left computes $ y := A x + y $ via dot products and the one on the right computes $ y := A^T x + y $ via dot products.  You are to implement the one on the right.

## The routine <br> <code> Mvmult_t_unb_var1( A, x, y ) </code>

This routine, given $ A \in \mathbb{R}^{m \times m} $, $ x \in \mathbb{R}^m $, and $ y \in \mathbb{R}^m $, computes $ y := A^T x + y $.  The "_t_" in the name of the routine indicates this is the "transpose" matrix-vector multiplication.  

The specific laff functions we will use are 
<ul>
<li> <code> laff.dots( x, y, alpha ) </code> which computes $ \alpha := x^T y + \alpha $.  </li>
</ul>

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage</a> to generate a code skeleton.  (Make sure you adjust the name of the routine.)

In [1]:
import flame
import laff as laff

def Mvmult_t_unb_var1(A, x, y):

    AL, AR = flame.part_1x2(A, \
                            0, 'LEFT')

    yT, \
    yB  = flame.part_2x1(y, \
                         0, 'TOP')

    while AL.shape[1] < A.shape[1]:

        A0, a1, A2 = flame.repart_1x2_to_1x3(AL, AR, \
                                             1, 'RIGHT')

        y0,   \
        psi1, \
        y2    = flame.repart_2x1_to_3x1(yT, \
                                        yB, \
                                        1, 'BOTTOM')

        #------------------------------------------------------------#

        laff.dots(a1, x, psi1)

        #------------------------------------------------------------#

        AL, AR = flame.cont_with_1x3_to_1x2(A0, a1, A2, \
                                            'LEFT')

        yT, \
        yB  = flame.cont_with_3x1_to_2x1(y0,   \
                                         psi1, \
                                         y2,   \
                                         'TOP')

    flame.merge_2x1(yT, \
                    yB, y)

## Testing

Let's quickly test the routine by creating a 3 x 4 matrix and related vectors, performing the computation.

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 3,4 ) )
x = matrix( random.rand( 3,1 ) )
y = matrix( random.rand( 4,1 ) )
yold = matrix( random.rand( 4,1 ) )

print( 'A before =' )
print( A )

print( 'x before =' )
print( x )

print( 'y before =' )
print( y )

A before =
[[0.65172132 0.55823012 0.8617082  0.25669227]
 [0.94794816 0.56053487 0.10085845 0.86007394]
 [0.06848067 0.02485671 0.65976334 0.87826993]]
x before =
[[0.79915422]
 [0.48516732]
 [0.55825869]]
y before =
[[0.53069318]
 [0.51464584]
 [0.55118804]
 [0.78559288]]


In [3]:
from numpy import transpose

laff.copy( y, yold )   # save the original vector y

Mvmult_t_unb_var1( A, x, y )

print( 'y after =' )
print( y )

print( 'y - ( transpose( A ) * x + yold ) = ' )
print( y - ( transpose( A ) * x + yold ) )

y after =
[[1.54966242]
 [1.24658747]
 [1.65707762]
 [1.89831117]]
y - ( transpose( A ) * x + yold ) = 
[[-2.22044605e-16]
 [-2.22044605e-16]
 [ 2.22044605e-16]
 [ 0.00000000e+00]]


Bingo, it seems to work!  (Notice that we are doing floating point computations, which means that due to rounding you may not get an exact "0".)

## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.

## Algorithm (via <code>axpy</code>s)

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/431Mvmult_n_unb_var2.png" alt="Matrix-vector multiplication via axpys algorithm" width="55%"><image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/431Mvmult_t_unb_var2.png" alt="Matrix-vector multiplication via dot axpys algorithm" width="45%">

Above, you find two algorithms.  The one on the left computes $ y := A x + y $ via <code> axpy</code>s and the one on the right computes $ y := A^T x + y $ via <code> axpy</code>s.  You are to implement the one on the right.

## The routine <br> <code> Mvmult_t_unb_var2( A, x, y ) </code>

This routine, given $ A \in \mathbb{R}^{m \times m} $, $ x \in \mathbb{R}^m $, and $ y \in \mathbb{R}^m $, computes $ y := A^T x + y $.  The "_t_" in the name of the routine indicates this is the "transpose" matrix-vector multiplication.  

The specific laff functions we will use are 
<ul>
<li> <code> laff.axpy( alpha, x, y ) </code> which computes $ y := \alpha x + y $.  </li>
</ul>

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage</a> to generate a code skeleton.  (Make sure you adjust the name of the routine.)

In [4]:
def Mvmult_t_unb_var2(A, x, y):

    AT, \
    AB  = flame.part_2x1(A, \
                         0, 'TOP')

    xT, \
    xB  = flame.part_2x1(x, \
                         0, 'TOP')

    while AT.shape[0] < A.shape[0]:

        A0,  \
        a1t, \
        A2   = flame.repart_2x1_to_3x1(AT, \
                                       AB, \
                                       1, 'BOTTOM')

        x0,   \
        chi1, \
        x2    = flame.repart_2x1_to_3x1(xT, \
                                        xB, \
                                        1, 'BOTTOM')

        #------------------------------------------------------------#

        laff.axpy(chi1, a1t, y)

        #------------------------------------------------------------#

        AT, \
        AB  = flame.cont_with_3x1_to_2x1(A0,  \
                                         a1t, \
                                         A2,  \
                                         'TOP')

        xT, \
        xB  = flame.cont_with_3x1_to_2x1(x0,   \
                                         chi1, \
                                         x2,   \
                                         'TOP')

## Testing

Let's quickly test the routine by creating a 3 x 4 matrix and related vectors, performing the computation.

In [5]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 3,4 ) )
x = matrix( random.rand( 3,1 ) )
y = matrix( random.rand( 4,1 ) )
yold = matrix( random.rand( 4,1 ) )

print( 'A before =' )
print( y )

print( 'x before =' )
print( x )

print( 'y before =' )
print( y )

A before =
[[0.09588204]
 [0.40930986]
 [0.98037535]
 [0.10177008]]
x before =
[[0.50673859]
 [0.03164391]
 [0.60130129]]
y before =
[[0.09588204]
 [0.40930986]
 [0.98037535]
 [0.10177008]]


In [6]:
from numpy import transpose

laff.copy( y, yold )   # save the original vector y

Mvmult_t_unb_var2( A, x, y )

print( 'y after =' )
print( y )

print( 'y - ( transpose( A ) * x + yold ) = ' )
print( y - ( transpose( A ) * x + yold ) )

y after =
[[0.52890576]
 [1.22869051]
 [1.43746968]
 [0.86256279]]
y - ( transpose( A ) * x + yold ) = 
[[0.]
 [0.]
 [0.]
 [0.]]


Bingo, it seems to work!  (Notice that we are doing floating point computations, which means that due to rounding you may not get an exact "0".)

## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.